import os
import time
import requests
import random
import tweepy
import google.generativeai as genai

# -----------------------------
# ENV KEYS
# -----------------------------
API_KEY       = os.getenv("API_KEY")       # Twitter
API_SECRET    = os.getenv("API_SECRET")    # Twitter
ACCESS_TOKEN  = os.getenv("ACCESS_TOKEN")  # Twitter
ACCESS_SECRET = os.getenv("ACCESS_SECRET") # Twitter
GEMINI_KEY    = os.getenv("GEMINI_KEY")    # Gemini

# HORDE_KEY opsiyoneldir. Yoksa Anonim (0000000000) kullanılır.
# Kendi keyinizi alırsanız (stablehorde.net) daha hızlı resim üretir.
HORDE_KEY     = os.getenv("HORDE_KEY", "0000000000") 

if not GEMINI_KEY:
    print("ERROR: GEMINI_KEY eksik!")
    exit(1)

# -----------------------------
# 1. GEMINI PROMPT GENERATOR
# -----------------------------
def generate_prompt_caption():
    genai.configure(api_key=GEMINI_KEY)
    model = genai.GenerativeModel("gemini-2.0-flash")

    themes = [
        "Cyberpunk City Rain",
        "Ethereal Forest Magic",
        "Space Colony on Mars",
        "Underwater Ancient Ruins",
        "Steampunk Airship Adventure",
        "Vaporwave Sunset Road",
        "Gothic Vampire Castle"
    ]

    theme = random.choice(themes)

    prompt = f"""
    Write a prompt for an AI image generator based on this theme: {theme}.
    Return exactly two lines:
    PROMPT: <english detailed description>
    CAPTION: <short tweet caption>
    """
    
    try:
        text = model.generate_content(prompt).text
        parts = text.split("CAPTION:")
        
        img_prompt = parts[0].replace("PROMPT:", "").strip()
        caption = parts[1].strip() if len(parts) > 1 else f"{theme} #AI"

        # Kalite artırıcı tagler
        final_prompt = f"{img_prompt}, masterpiece, best quality, ultra detailed, 8k, cinematic lighting"
        
        return final_prompt, caption
    except Exception as e:
        print(f"Gemini Hatası: {e}")
        return f"A beautiful {theme}", f"{theme} generated by AI"


# -----------------------------
# 2. AI HORDE IMAGE GENERATOR (BEDAVA & GPU AĞI)
# -----------------------------
def generate_image_horde(prompt_text):
    print("AI Horde → İstek gönderiliyor (Sıra beklenecek)...")
    
    # Adım 1: İsteği Gönder (Task Oluştur)
    generate_url = "https://stablehorde.net/api/v2/generate/async"
    
    headers = {
        "apikey": HORDE_KEY,
        "Client-Agent": "MyTwitterBot:v1.0"
    }
    
    payload = {
        "prompt": prompt_text,
        "params": {
            "sampler_name": "k_euler",
            "cfg_scale": 7,
            "width": 576,    # Horde'da ücretsizler için güvenli boyutlar
            "height": 1024,  # Dikey (9:16) format
            "steps": 30,
        },
        "nsfw": False,
        "censor_nsfw": True,
        "models": ["SDXL_beta::stability.ai#6901"] # SDXL Modeli
        # Eğer SDXL yavaş gelirse ["stable_diffusion"] yazabilirsiniz.
    }

    try:
        req = requests.post(generate_url, json=payload, headers=headers)
        if req.status_code != 202:
            print(f"Horde Gönderim Hatası: {req.text}")
            return None
            
        task_id = req.json()['id']
        print(f"Görev alındı ID: {task_id}. İşlenmesi bekleniyor...")
    except Exception as e:
        print(f"Bağlantı Hatası: {e}")
        return None

    # Adım 2: Bekleme Döngüsü (Polling)
    # Resim bitene kadar her 5 saniyede bir soracağız.
    wait_time = 0
    max_wait = 120 # En fazla 2 dakika bekle
    
    while wait_time < max_wait:
        time.sleep(5)
        wait_time += 5
        
        status_url = f"https://stablehorde.net/api/v2/generate/status/{task_id}"
        check = requests.get(status_url)
        status_data = check.json()
        
        if status_data['done']:
            print("İşlem tamamlandı! Resim indiriliyor...")
            # Resim URL'sini al
            generations = status_data['generations']
            if len(generations) > 0:
                img_url = generations[0]['img']
                return requests.get(img_url).content
            else:
                print("Horde resim üretmedi (Hata).")
                return None
        
        print(f"Bekleniyor... ({status_data['wait_time']}sn tahmini süre)")

    print("Zaman aşımı! Resim çok uzun sürdü.")
    return None


# -----------------------------
# 3. TWITTER POST
# -----------------------------
def post_to_twitter(img_bytes, caption):
    filename = "horde_image.png"
    with open(filename, "wb") as f:
        f.write(img_bytes)

    try:
        auth = tweepy.OAuthHandler(API_KEY, API_SECRET)
        auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)
        api = tweepy.API(auth)
        
        print("Twitter'a yükleniyor...")
        media = api.media_upload(filename)
        
        client = tweepy.Client(
            consumer_key=API_KEY,
            consumer_secret=API_SECRET,
            access_token=ACCESS_TOKEN,
            access_token_secret=ACCESS_SECRET
        )

        client.create_tweet(
            text=caption + " #AIHorde #SDXL #Art",
            media_ids=[media.media_id]
        )
        print("TWEET BAŞARILI!")
        
    except Exception as e:
        print(f"Twitter Hatası: {e}")
    finally:
        if os.path.exists(filename):
            os.remove(filename)

# -----------------------------
# MAIN
# -----------------------------
if __name__ == "__main__":
    prompt, caption = generate_prompt_caption()
    print("-" * 30)
    print("Prompt:", prompt)
    print("-" * 30)
    
    img_data = generate_image_horde(prompt)
    
    if img_data:
        post_to_twitter(img_data, caption)
    else:
        print("Görsel oluşturulamadı.")
        
